[package]
name = "sessidx"
version = "0.0.1"
edition = "2024"
rust-version = "1.98"
publish = false
license = "MIT"
repository = "https://github.com/Entwining/sessidx"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
allow_attributes_without_reason = "warn"
dbg_macro = "warn"
todo = "warn"

[dependencies]
brush-parser = "=0.4.0"
rusqlite = { version = "=0.32.1", features = ["bundled", "hooks"] }
serde_json = { version = "=1.0.151", features = ["raw_value"] }
serde = { version = "=1.0.228", features = ["derive"] }
anyhow = "=1.0.103"
regex = "=1.12.2"
chrono = { version = "=0.4.42", default-features = false, features = ["std", "clock", "serde"] }
sha2 = { version = "=0.11.0", default-features = false }
walkdir = "=2.5.0"
clap = { version = "=4.5.54", features = ["derive"] }
hex = "=0.4.3"

[dev-dependencies]
tempfile = "=3.23.0"
